---

- name: PBS - add SMS server to pbs.conf
  lineinfile:
    path: /etc/pbs.conf
    regexp: '^PBS_SERVER='
    line: 'PBS_SERVER={{sms_name}}'

- name: PBS - enable server in pbs.conf
  lineinfile:
    path: /etc/pbs.conf
    regexp: '^PBS_START_SERVER='
    line: 'PBS_START_SERVER=1'

- name: PBS - enable scheduler in pbs.conf
  lineinfile:
    path: /etc/pbs.conf
    regexp: '^PBS_START_SCHED='
    line: 'PBS_START_SCHED=1'

- name: PBS - enable comm in pbs.conf
  lineinfile:
    path: /etc/pbs.conf
    regexp: '^PBS_START_COMM='
    line: 'PBS_START_COMM=1'

- name: PBS - enable mom in pbs.conf
  lineinfile:
    path: /etc/pbs.conf
    regexp: '^PBS_START_SERVER='
    line: 'PBS_START_MOM=1'
  when: sms_accept_jobs == 'yes'

- name: PBS - disable mom in pbs.conf
  lineinfile:
    path: /etc/pbs.conf
    regexp: '^PBS_START_SERVER='
    line: 'PBS_START_MOM=0'
  when: sms_accept_jobs == 'no'

- name: PBS - enable and start server
  service:
    name: pbs
    enabled: yes
    state: started
