---

- name: OpenHPC - install yum-config-manager
  yum:
    name: yum-config-manager
    state: present
  when: ohpc_local_mirror

- name: OpenHPC Node - add repo mirror hosted on SMS
  shell: "yum-config-manager --add-repo=http://{{sms_ip}}/{{ohpc_repo_dir}}/OpenHPC.local.repo"
  when: ohpc_local_mirror

- name: OpenHPC - replace local path with SMS URL
  shell: perl -pi -e 's/file:\/\/\@PATH\@/http:\/\/{{sms_ip}}"{{ohpc_repo_dir}}//\//"\/"}"/s' /etc/yum.repos.d/OpenHPC.local.repo
  when: ohpc_local_mirror

- name: OpenHPC - install repository release 1.3
  yum:
    name: http://build.openhpc.community/OpenHPC:/1.3/CentOS_7/x86_64/ohpc-release-1.3-1.el7.x86_64.rpm
    state: present
  when: not ohpc_local_mirror

- name: OpenHPC - install ohpc-base via Yum
  yum:
    name: "{{item}}"
    state: present
  with_items:
    - epel-release
    - ohpc-base