---


- name: OpenHPC - install repository release 1.3
  yum:
    name: http://build.openhpc.community/OpenHPC:/1.3/CentOS_7/x86_64/ohpc-release-1.3-1.el7.x86_64.rpm
    state: present
  when: ohpc_local_mirror == no

- name: OpenHPC - install ohpc-base via Yum
  yum:
    name: "{{item}}"
    state: present
  with_items:
    - epel-release
    - ohpc-base
