---

- name: OpenHPC - create directory for local repository
  file:
    path: "{{ohpc_repo_dir}}"
    state: directory
    mode: 0755

- name: OpenHPC - download and extract tarball
  unarchive:
    src: http://build.openhpc.community/dist/1.3.4/OpenHPC-1.3.4.CentOS_7.x86_64.tar
    dest: "{{ohpc_repo_dir}}"
    remote_src: yes

- name: OpenHPC - initialise local mirror repository
  command: "{{ohpc_repo_dir}}/make_repo.sh"
