---

- name: xCAT - register internal provisioning interface for DHCP
  command: 'chdef -t site dhcpinterfaces="xcatmn|{{sms_eth_internal}}"'

- name: xCAT - import node OS install media
  command: 'copycds {{iso_path}}'

- name: xCAT - set node root password
  command: "chtab key=system passwd.username=root passwd.password={{node_root_password}}"

- name: xCAT - set domain name
  command: "chdef -t site domain={{domain_name}}"

- name: xCAT - set Infiniband network
  command: "chdef -t network -o ib0 mask={{ipoib_netmask}} net={{sms_ipoib}}"
  when: ipoib

- name: xCAT - query netboot image for stateless cluster
  shell: "lsdef -t osimage | grep netboot | awk '{print $1}'"
  register: osimage
  when: xcat_mode == 'stateless'

- name: xCAT - build initial chroot image for stateless cluster
  command: "genimage {{osimage.stdout_lines[0]}}"
  when: xcat_mode == 'stateless'
