---

- name: "Repositories - add online repositories to /etc/yum.repos.d"
  yum_repository:
    name: "{{ item }}"
    description: "Online repository for {{ item }}"
    baseurl: "{{ yum_repos[item] }}"
    state: present
  with_items: "{{ yum_repos }}"
  when: repository_type == 'online'

- name: "Repositories - add cache repositories to /etc/yum.repos.d"
  yum_repository:
    name: "{{ item }}"
    description: "Cache repository on SMS for {{ item }}"
    baseurl: "{{ yum_repos[item] | regex_replace(yum_repos[item].rpartition("//")[-1].partition("/")[0], item+'_cache.'+sms_name+'.'+domain_name) }}"
    state: present
  with_items: "{{ yum_repos }}"
  when: repository_type == 'cache'