---

- name: "Repositories - add online repositories to /etc/yum.repos.d"
  yum_repository:
    name: "{{ item }}"
    description: "Online repository for {{ item }}"
    baseurl: "{{ yum_repos[item] }}"
    state: present
  with_items: "{{ yum_repos }}"
  when: repository_type == 'online'