---

- name: "Repositories - add online repositories to /etc/yum.repos.d"
  yum_repository:
    name: "{{ item }}"
    description: "Online repository for {{ item }}"
    baseurl: "{{ yum_repos[item] }}"
    gpgkey: "{{ yum_repos[item].key }}"
    gpgcheck: yes
    state: present
  with_items: "{{ yum_repos }}"
  when: repository_type == 'online'

- name: "Repositories - add cache repositories to /etc/yum.repos.d"
  yum_repository:
    name: "{{ item }}"
    description: "Cache repository on SMS for {{ item }}"
    baseurl: "{{ yum_repos[item].url | regex_replace(yum_repos[item].url.rpartition('//')[-1].partition('/')[0], item+'_cache.'+sms_name+'.'+domain_name+':'+cache_port) }}"
    gpgkey: "{{ yum_repos[item].key }}"
    gpgcheck: yes
    state: present
  with_items: "{{ yum_repos }}"
  when: repository_type == 'cache'

- name: "Repositories - add the SMS local repository to /etc/yum.repos.d"
  yum_repository:
    name: "sms_local_repo"
    description: "Local repository to distribute individual RPMs to the cluster"
    baseurl: "http://{{ sms_ip }}//install/local_repo/"
    gpgcheck: no
    state: present
  when: hostvars[inventory_hostname].group_names[0] == "nodes"

- name: "Repositories - remove upstream CentOS repositories"
  command: "rm -rf /etc/yum.repos.d/CentOS-*.repo"
  when: hostvars[inventory_hostname].group_names[0] == "nodes"