---

- name: "Repositories - add online repositories to /etc/yum.repos.d"
  yum_repository:
    name: "{{ item }}"
    description: "Online repository for {{ item }}"
    baseurl: "{{ yum_repos[item].url }}"
    gpgkey: "{{ yum_repos[item].key }}"
    gpgcheck: yes
    state: present
  with_items: "{{ yum_repos }}"
  when: repository_type == 'online' or repository_type == 'cache'

- name: "Repositories - set the Yum proxy to the local cache"
  lineinfile:
    dest: /etc/yum.conf
    state: present
    regexp: "proxy=.*"
    insertafter: EOF
    line: "proxy=http://{{ proxy_host }}:{{ proxy_port }}/"
  when: repository_type == 'cache'

- name: "Repositories - add the SMS local repository to /etc/yum.repos.d"
  yum_repository:
    name: "sms_local_repo"
    description: "Local repository to distribute individual RPMs to the cluster"
    baseurl: "http://{{ sms_ip }}//install/local_repo/"
    gpgcheck: no
    state: present
  when: hostvars[inventory_hostname].group_names[0] == "nodes"

- name: "Repositories - remove upstream CentOS repositories"
  command: "rm -rf /etc/yum.repos.d/CentOS-*.repo"
  when: hostvars[inventory_hostname].group_names[0] == "nodes"
